name: Build Client

on:
  push:
    branches:
      - 'dev/*'
    tags:
      - 'v*'

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      working-directory: ./Vatis.Client
      run: |
        dotnet publish --runtime win-x64 --self-contained true --configuration Release --framework net6.0-windows `
        -p:PublishSingleFile=true -p:PublishReadyToRun=true --output ./publish

    - name: Client Hash
      run: |
        $hash = (Get-FileHash .\Vatis.Client\publish\vATIS.exe -Algorithm SHA256).Hash.ToLower()
        echo "CLIENT_HASH=$hash" >> $env:GITHUB_ENV

    - name: Checkout VatsimAuth
      uses: actions/checkout@v3
      with:
        repository: vatis-project/auth
        path: auth
        token: ${{ secrets.GH_TOKEN }}

    - name: VatsimAuth CMake
      working-directory: auth
      run: |
        cmake -E make_directory build
        cd build
        cmake .. -DCLIENT_HASH=${{ env.CLIENT_HASH }} -DVATSIM_CLIENT_ID=${{ secrets.CLIENT_ID }} -DVATSIM_CLIENT_KEY=${{ secrets.CLIENT_KEY }}
        cmake --build . --config RelWithDebInfo

    - name: Copy Client Files
      run: |
        Copy-Item -Path .\auth\build\RelWithDebInfo\VatsimAuth.dll -Destination .\Vatis.Client\publish\
        Copy-Item -Path .\airports.json -Destination .\Vatis.Client\publish\
        Copy-Item -Path .\navaids.json -Destination .\Vatis.Client\publish\

    - name: Get Client Version
      run: |
        $path = ls .\Vatis.Client\publish\*.exe | select -First 1 | % fullname
        $version = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($path).ProductVersion
        echo "CLIENT_VER=$version" >> $env:GITHUB_ENV
        "!define Version ""$version""" | Out-File -FilePath .\Version.txt

    - name: Create Installer
      uses: joncloud/makensis-action@v3.6
      with:
        script-file: '.\installer.nsi'

    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        path: vATIS-Setup-${{ env.CLIENT_VER }}.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        name: vATIS ${{ env.CLIENT_VER }}
        prerelease: true
        draft: true
        files: vATIS-Setup-${{ env.CLIENT_VER }}.exe
